title: Musicians of Manoa
description: Connecting the musical talents of UH Manoa
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/musicians-of-manoa/musicians-of-manoa.github.io
